config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root "transactions#index"

  devise_for :users, :controllers => {:omniauth_callbacks => "callbacks"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :file_uploads, only: [:create, :new]

  resources :transactions, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_upload.rb
class FileUpload
  include ActiveModel::Model

  attr_accessor :file, :user

  validates :user, presence: true
  validates :file, presence: true
  validate :file_validation

  def file_validation
    errors.add(:file, "Invalid extension") unless file.class == ActionDispatch::Http::UploadedFile && file.content_type == 'application/octet-stream'
  end

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  validates :item_price, :purchaser_name, :item_description, :purchase_count, 
            :merchant_address, :user_id, :merchant_name, presence: true

  validates_numericality_of :item_price, greater_than_or_equal_to: 0
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :transactions


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController

  def new
    @file = FileUpload.new
  end

  def create
    @file = FileUpload.new(file_params)
    if @file.valid?
      file_string = File.read(file_params[:file].path)
      AddTransactionJob.perform_later(file_string, file_params[:user][:id])
      redirect_to new_file_upload_path, notice: "Transação foi arquivada no sistema!"
    else
      render :new
    end
  end

  private

  def file_params
    params.require(:file_upload).permit(:file).merge(user: current_user)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    transactions = current_user.transactions
    @transactions = transactions.paginate(page: params[:page], per_page: 15)
    @sum_values = transactions.sum(:item_price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/file_uploads/new.html.erb
<div class="container">
  <div class="row">
      <div class="notice">
        <%= notice %>
      </div>
    <%= form_for @file, multipart: true do |f| %>
    <% if @file.errors.any? %>
      <% @file.errors.full_messages.each do |message| %>
        <div class="message">
          <li><%= message %></li>
        </div>
      <% end %>
      <%end%>
      <%= f.label :file %>
      <%= f.file_field :file %>
      <%= f.submit "Enviar" %>
    <% end %>

    <%= link_to "Transações da conta", transactions_path%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nuuvem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<p>Lista de operações</p>

<p><%= link_to "Adicione um arquivo clicando aqui!", new_file_upload_path %></p>

<% if @transactions.present? %>
  <table>
    <tr>
      <th>Purchaser Name</th>
      <th>Purchaser Count</th>
      <th>Merchant name</th>
      <th>Merchant address</th>
      <th>Item Description</th>
      <th>Item Price</th>
    </tr>
      <% @transactions.each do |t| %>
        <tr>
          <td><%= t.purchaser_name %></td>
          <td><%= t.purchase_count %></td>
          <td><%= t.merchant_name %></td>
          <td><%= t.merchant_address %></td>
          <td><%= t.item_description %></td>
          <td><%= t.item_price %></td>
        </tr>
      <%end%>
  </table>
  <p>Valor total disponível: <%= @sum_values %></p>
  <%= will_paginate @transactions %>
<%else%>
  <span>Não há transações registradas para este usuário. Atualize a página!</span>
<%end%>

